pipeline {
    environment {
        APP_NAME = "my-python-app"
    }

    stages {
        stage('Tag Prod') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'my-quay', passwordVariable: 'QUAY_PASSWORD', usernameVariable: 'QUAY_USERNAME')]) {
                    sh '''
                        echo "$QUAY_PASSWORD" | docker login quay.io -u "$QUAY_USERNAME" --password-stdin
                        curl -s "https://quay.io/api/v1/repository/$QUAY_USERNAME/$APP_NAME/tag/" | jq -r '.tags[].name' | sort -u
                        docker logout quay.io
                    '''
                }
            }
        }
    }
}
