pipeline {
    stages {
        stage('Tag Prod') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'my-quay', passwordVariable: 'QUAY_PASSWORD', usernameVariable: 'QUAY_USERNAME')]) {
                    sh '''
                        echo "$QUAY_PASSWORD" | docker login quay.io -u "$QUAY_USERNAME" --password-stdin
                        docker pull quay.io/$QUAY_USERNAME/$APP_NAME:$APP_VERSION
                        docker tag quay.io/$QUAY_USERNAME/$APP_NAME:$APP_VERSION quay.io/$QUAY_USERNAME/$APP_NAME:prod-$APP_VERSION
                        docker push quay.io/$QUAY_USERNAME/$APP_NAME:prod-$APP_VERSION
                        docker tag quay.io/$QUAY_USERNAME/$APP_NAME:$APP_VERSION quay.io/$QUAY_USERNAME/$APP_NAME:stable
                        docker push quay.io/$QUAY_USERNAME/$APP_NAME:stable
                        curl -s "https://quay.io/api/v1/repository/$QUAY_USERNAME/$APP_NAME/tag/" | jq -r '.tags[].name' | sort -u
                        docker logout quay.io
                    '''
                }
            }
        }
    }
}
