pipeline {
    agent any

    environment {
        APP_NAME = "my-python-app"
        QUAY_ORG = "jenkinscapstone"
    }

    stages {
        stage('List Prod Builds') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'my-quay', passwordVariable: 'QUAY_PASSWORD', usernameVariable: 'QUAY_USERNAME')]) {
                    sh '''
                        echo "$QUAY_PASSWORD" | docker login quay.io -u "$QUAY_USERNAME" --password-stdin
                    CURRENT_PROD=$(curl -s "https://quay.io/api/v1/repository/$QUAY_ORG/$APP_NAME/tag/" \
                            | jq -r '.tags[].name | select(startswith("prod-"))' \
                            | sort -Vr \
                            | head -n 1)
                        echo "Current prod tag: $CURRENT_PROD"
                        ROLLBACK_PROD=$(curl -s "https://quay.io/api/v1/repository/$QUAY_ORG/$APP_NAME/tag/" \
                            | jq -r '.tags[].name | select(startswith("prod-"))' \
                            | sort -Vr \
                            | head -n 2 | tail -n 1)
                        echo "Rollback prod tag: $ROLLBACK_PROD"
                        docker pull quay.io/$QUAY_ORG/$APP_NAME:$ROLLBACK_PROD

                        docker tag \
                            quay.io/$QUAY_ORG/$APP_NAME:$ROLLBACK_PROD \
                            quay.io/$QUAY_ORG/$APP_NAME:stable

                        docker push \
                            quay.io/$QUAY_ORG/$APP_NAME:stable
                        docker logout quay.io
                    '''
                }
            }
        }
    }
}
